### ISSUE TITLE
Add a proper support for Vanilla Subsonic

### ISSUE THREAD

**Issue by rollecode** [ronilaukkarinen/rolleshark#2]
Fix and test with latest Subsonic. As requested by Eric Basta.

**Comment by rollecode** [comment]
@ebasta I added support for Subsonic Vanilla. However, it has quite a different structure when compared to MusicCabinet, so it's not perfect, but close enough. For example music album covers are much bigger in Vanilla, so I would have to create graphics for those separately. 

I won't do much more customizations to Vanilla for now, because I want to retain primary support for Musiccabinet. I hope this is ok for you!

**Comment by ghost** [comment]
I've attached some screen grabs to see problem
areas - but if you could point me to the correct files I can look to
correct these and upload the fixes. Thank you so much - so wonderful
to have this theme back!

**Comment by rollecode** [comment]
Attachments are not coming through with Github issue tracker (this email thread), so please send them to my email: roni@dude.fi. Thanks!

**Comment by rollecode** [comment]
@ebasta Just pushed a bunch of fixes, even added the vinyl covers for Vanilla. Played some albums and it looks good for me. Please note this theme is not meant to be responsive, because of the deprecated HTML structure and missing classes it is just too much work and there's already [Jamstash](http://beta.jamstash.com) available. I hope rolleshark works better for you after the updates.
